# Generated by Django 4.2.11 on 2024-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_id_alter_image_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
