# Generated by Django 4.2.11 on 2024-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
