# Generated by Django 4.2.11 on 2024-04-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_news_newsimages_newscomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.news'),
        ),
    ]
